//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Game/Settings/ControlMaps/TouchControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchControlMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchControlMap"",
    ""maps"": [
        {
            ""name"": ""TouchActionMap"",
            ""id"": ""d1669231-1195-41d8-b874-207abe226d37"",
            ""actions"": [
                {
                    ""name"": ""Touch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""09509a72-138b-4e20-ad94-91b7a9ab7545"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slide"",
                    ""type"": ""Value"",
                    ""id"": ""304b7929-9c60-4393-84a7-39a75e5c703a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchContact"",
                    ""type"": ""Button"",
                    ""id"": ""14cd3ef2-854d-4b66-a7a6-6334304088ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""963a2517-110c-4f65-af76-476cedab760f"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc45a627-39a1-401a-a400-126dec27a23a"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b31595c-3067-4579-a2a1-a3ab50ed1455"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TouchActionMap
        m_TouchActionMap = asset.FindActionMap("TouchActionMap", throwIfNotFound: true);
        m_TouchActionMap_Touch = m_TouchActionMap.FindAction("Touch", throwIfNotFound: true);
        m_TouchActionMap_Slide = m_TouchActionMap.FindAction("Slide", throwIfNotFound: true);
        m_TouchActionMap_TouchContact = m_TouchActionMap.FindAction("TouchContact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TouchActionMap
    private readonly InputActionMap m_TouchActionMap;
    private ITouchActionMapActions m_TouchActionMapActionsCallbackInterface;
    private readonly InputAction m_TouchActionMap_Touch;
    private readonly InputAction m_TouchActionMap_Slide;
    private readonly InputAction m_TouchActionMap_TouchContact;
    public struct TouchActionMapActions
    {
        private @TouchControlMap m_Wrapper;
        public TouchActionMapActions(@TouchControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch => m_Wrapper.m_TouchActionMap_Touch;
        public InputAction @Slide => m_Wrapper.m_TouchActionMap_Slide;
        public InputAction @TouchContact => m_Wrapper.m_TouchActionMap_TouchContact;
        public InputActionMap Get() { return m_Wrapper.m_TouchActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActionMapActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActionMapActions instance)
        {
            if (m_Wrapper.m_TouchActionMapActionsCallbackInterface != null)
            {
                @Touch.started -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnTouch;
                @Touch.performed -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnTouch;
                @Touch.canceled -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnTouch;
                @Slide.started -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnSlide;
                @Slide.performed -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnSlide;
                @Slide.canceled -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnSlide;
                @TouchContact.started -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnTouchContact;
                @TouchContact.performed -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnTouchContact;
                @TouchContact.canceled -= m_Wrapper.m_TouchActionMapActionsCallbackInterface.OnTouchContact;
            }
            m_Wrapper.m_TouchActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Touch.started += instance.OnTouch;
                @Touch.performed += instance.OnTouch;
                @Touch.canceled += instance.OnTouch;
                @Slide.started += instance.OnSlide;
                @Slide.performed += instance.OnSlide;
                @Slide.canceled += instance.OnSlide;
                @TouchContact.started += instance.OnTouchContact;
                @TouchContact.performed += instance.OnTouchContact;
                @TouchContact.canceled += instance.OnTouchContact;
            }
        }
    }
    public TouchActionMapActions @TouchActionMap => new TouchActionMapActions(this);
    public interface ITouchActionMapActions
    {
        void OnTouch(InputAction.CallbackContext context);
        void OnSlide(InputAction.CallbackContext context);
        void OnTouchContact(InputAction.CallbackContext context);
    }
}
